-- Travel Hub Supabase foundation
-- Run this once in Supabase SQL Editor after creating the project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  phone text,
  age integer,
  city text,
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trips (
  id text primary key,
  name text not null,
  short text,
  status text not null default 'wishlist' check (status in ('completed','upcoming','ongoing','wishlist','cancelled')),
  start_date date,
  end_date date,
  place text,
  country text not null default 'India',
  state text,
  latitude double precision,
  longitude double precision,
  summary text,
  experience text,
  budget numeric(12,2) not null default 0,
  capacity integer not null default 1 check (capacity > 0),
  icon text,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trip_members (
  id bigint generated by default as identity primary key,
  trip_id text not null references public.trips(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  member_name text not null,
  is_verified boolean not null default false,
  joined_at timestamptz not null default now(),
  unique (trip_id, user_id),
  unique (trip_id, member_name)
);

create table if not exists public.trip_applications (
  id bigint generated by default as identity primary key,
  trip_id text not null references public.trips(id) on delete cascade,
  applicant_id uuid references public.profiles(id) on delete set null,
  name text not null,
  phone text not null,
  age integer,
  city text,
  message text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null
);

create table if not exists public.itinerary_days (
  id bigint generated by default as identity primary key,
  trip_id text not null references public.trips(id) on delete cascade,
  day_number integer not null,
  title text not null,
  description text,
  unique (trip_id, day_number)
);

create table if not exists public.itinerary_activities (
  id bigint generated by default as identity primary key,
  itinerary_day_id bigint not null references public.itinerary_days(id) on delete cascade,
  sort_order integer not null default 0,
  title text not null,
  description text,
  start_time time
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  trip_id text references public.trips(id) on delete set null,
  author_id uuid references public.profiles(id) on delete set null,
  author_name text not null,
  title text not null,
  body text not null,
  status text not null default 'approved' check (status in ('pending','approved','rejected')),
  wall_x double precision not null default 0,
  wall_y double precision not null default 0,
  rotation double precision not null default 0,
  scale double precision not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  trip_id text references public.trips(id) on delete set null,
  type text not null default 'photo' check (type in ('photo','video')),
  title text not null,
  url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_requests (
  id bigint generated by default as identity primary key,
  type text not null,
  trip_id text references public.trips(id) on delete set null,
  name text not null,
  destination text,
  date date,
  people integer,
  phone text,
  age integer,
  city text,
  message text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  type text not null default 'info',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name',
             new.raw_user_meta_data ->> 'name',
             split_part(coalesce(new.email,''), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.trips enable row level security;
alter table public.trip_members enable row level security;
alter table public.trip_applications enable row level security;
alter table public.itinerary_days enable row level security;
alter table public.itinerary_activities enable row level security;
alter table public.memories enable row level security;
alter table public.media enable row level security;
alter table public.site_requests enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "public read trips" on public.trips;
create policy "public read trips" on public.trips for select using (true);
drop policy if exists "admins manage trips" on public.trips;
create policy "admins manage trips" on public.trips for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users read profiles" on public.profiles;
create policy "users read profiles" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update to authenticated using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
drop policy if exists "admins manage profiles" on public.profiles;
create policy "admins manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read approved members" on public.trip_members;
create policy "public read approved members" on public.trip_members for select using (is_verified = true);
drop policy if exists "admins manage members" on public.trip_members;
create policy "admins manage members" on public.trip_members for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users create own applications" on public.trip_applications;
create policy "users create own applications" on public.trip_applications for insert to authenticated with check (applicant_id = auth.uid());
drop policy if exists "users read own applications" on public.trip_applications;
create policy "users read own applications" on public.trip_applications for select to authenticated using (applicant_id = auth.uid() or public.is_admin());
drop policy if exists "admins manage applications" on public.trip_applications;
create policy "admins manage applications" on public.trip_applications for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read itinerary" on public.itinerary_days;
create policy "public read itinerary" on public.itinerary_days for select using (true);
drop policy if exists "admins manage itinerary" on public.itinerary_days;
create policy "admins manage itinerary" on public.itinerary_days for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "public read activities" on public.itinerary_activities;
create policy "public read activities" on public.itinerary_activities for select using (true);
drop policy if exists "admins manage activities" on public.itinerary_activities;
create policy "admins manage activities" on public.itinerary_activities for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read approved memories" on public.memories;
create policy "public read approved memories" on public.memories for select using (status = 'approved' or public.is_admin());
drop policy if exists "users create memories" on public.memories;
create policy "users create memories" on public.memories for insert to authenticated with check (author_id = auth.uid());
drop policy if exists "users update own memories" on public.memories;
create policy "users update own memories" on public.memories for update to authenticated using (author_id = auth.uid() or public.is_admin()) with check (author_id = auth.uid() or public.is_admin());
drop policy if exists "admins manage memories" on public.memories;
create policy "admins manage memories" on public.memories for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public read media" on public.media;
create policy "public read media" on public.media for select using (true);
drop policy if exists "admins manage media" on public.media;
create policy "admins manage media" on public.media for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users create requests" on public.site_requests;
create policy "users create requests" on public.site_requests for insert to authenticated with check (true);
drop policy if exists "users read own requests" on public.site_requests;
create policy "users read own requests" on public.site_requests for select to authenticated using (true);
drop policy if exists "admins manage requests" on public.site_requests;
create policy "admins manage requests" on public.site_requests for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users read own notifications" on public.notifications;
create policy "users read own notifications" on public.notifications for select to authenticated using (user_id = auth.uid() or public.is_admin());
drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications" on public.notifications for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

create index if not exists trip_applications_trip_id_idx on public.trip_applications(trip_id);
create index if not exists memories_trip_id_idx on public.memories(trip_id);
create index if not exists notifications_user_id_idx on public.notifications(user_id, created_at desc);
